// §source page/pkg/egress/sni_test.go
package egress

import (
	"bufio"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/binary"
	"errors"
	"fmt"
	"io"
	"math/big"
	"net"
	"net/http"
	"testing"
	"time"
)

// generateSelfSignedCert returns a self-signed TLS certificate for 127.0.0.1,
// generated at test time so the key material is always valid.
func generateSelfSignedCert(t *testing.T) tls.Certificate {
// §.splinter/page/pkg/egress/sni_test/generateSelfSignedCert.fs
}

// certPool returns a root pool trusting the self-signed cert.
func certPool(cert tls.Certificate) *x509.CertPool {
// §.splinter/page/pkg/egress/sni_test/certPool.fs
}

// TestParseClientHelloSNI verifies the SNI parser extracts the hostname from
// a real TLS ClientHello generated by crypto/tls.
func TestParseClientHelloSNI(t *testing.T) {
// §.splinter/page/pkg/egress/sni_test/TestParseClientHelloSNI.fs
}

// TestPeekSNINotTLS verifies peekSNI returns ErrNotTLS when the client sends
// non-TLS data, and that the peeked bytes are returned for relay.
func TestPeekSNINotTLS(t *testing.T) {
// §.splinter/page/pkg/egress/sni_test/TestPeekSNINotTLS.fs
}

// TestPeekSNIExtractsSNI verifies peekSNI returns the SNI from a real TLS
// ClientHello sent through a net.Pipe.
func TestPeekSNIExtractsSNI(t *testing.T) {
// §.splinter/page/pkg/egress/sni_test/TestPeekSNIExtractsSNI.fs
}

// TestHTTPProxyCONNECTSNIAllowed verifies a CONNECT tunnel with an allowed
// SNI reaches the upstream and relays data.
func TestHTTPProxyCONNECTSNIAllowed(t *testing.T) {
// §.splinter/page/pkg/egress/sni_test/TestHTTPProxyCONNECTSNIAllowed.fs
}

// TestHTTPProxyCONNECTSNIDenied verifies domain fronting is blocked: the
// CONNECT host is allowed, but the TLS SNI names a denied host.  The proxy
// must close the tunnel without forwarding any bytes to the upstream.
func TestHTTPProxyCONNECTSNIDenied(t *testing.T) {
// §.splinter/page/pkg/egress/sni_test/TestHTTPProxyCONNECTSNIDenied.fs
}

// TestHTTPProxyCONNECTSNIAllowedTLS verifies a CONNECT tunnel with an allowed
// SNI reaches a real TLS upstream and completes the handshake.
func TestHTTPProxyCONNECTSNIAllowedTLS(t *testing.T) {
// §.splinter/page/pkg/egress/sni_test/TestHTTPProxyCONNECTSNIAllowedTLS.fs
}

// TestSOCKS5CONNECTSNIDenied verifies SOCKS5 domain fronting is blocked:
// the SOCKS5 CONNECT host is allowed, but the TLS SNI names a denied host.
func TestSOCKS5CONNECTSNIDenied(t *testing.T) {
// §.splinter/page/pkg/egress/sni_test/TestSOCKS5CONNECTSNIDenied.fs
}

